CREATE TABLE tb_pizzas(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
sabor VARCHAR(100) NOT NULL,
descricao VARCHAR(255),
preco DECIMAL(6,2) NOT NULL,
borda VARCHAR(50) NOT NULL,
idCategoria BIGINT NOT NULL
);