CREATE TABLE tb_colaboradores(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cpf char(11) NOT NULL,
celular VARCHAR(13) NOT NULL,
cargo VARCHAR(50) NOT NULL,
salario DECIMAL(7,2) NOT NULL
);
